# 3_voxelization.py
# Voxelization of buildings with terrain-aware base elevation based on cutted data.
import argparse
from pathlib import Path
import math
import pickle
import os
import sys
import concurrent.futures
import time


import geopandas as gpd
from shapely.geometry import Polygon, MultiPolygon, Point
from shapely import affinity
import shapely
import numpy as np
import trimesh
from trimesh import boolean
import re
from auto_UTM import get_utm_crs_from_conf_raw
from dem_tif_to_shp import ensure_dem_shp_from_tif

_CORE_DIR = Path(__file__).resolve().parents[1]
if str(_CORE_DIR) not in sys.path:
    sys.path.insert(0, str(_CORE_DIR))

from deck_io import load_deck, parse_deck_text
from luw_progress import ProgressEmitter
from terr_voxel_gpu import (
    TerrainGpuKrigingUnavailable,
    gpu_kriging_backend_summary,
    gpu_kriging_requires_warmup,
    interpolate_points_kriging_cuda_chunk,
    warmup_gpu_kriging_kernel,
)
from terr_voxel_config import (
    ALLOWED_TERR_VOXEL_APPROACHES,
    resolve_terrain_voxel_config,
)

_PROGRESS = ProgressEmitter("Generating Voxel Domain")

def _parse_base_height_from_conf_raw(conf_raw: str) -> float | None:
    """
    Parse base_height from conf raw text if present.
    Mirrors core/bridge_core/1_buildBC.py behavior.
    """
    if not conf_raw:
        return None
    v = parse_deck_text(conf_raw).get_float("base_height")
    if v is None:
        return None
    if (not math.isfinite(v)) or (v < 0.0):
        return None
    return v

def _make_valid(geom):
    """
    Make geometry valid using shapely's make_valid or buffer(0) as fallback.
    """
    try:
        from shapely.validation import make_valid
        return make_valid(geom)
    except Exception:
        try:
            return geom.buffer(0)
        except Exception:
            return None


def _to_iter_polygons(geom):
    if geom is None:
        return []
    if isinstance(geom, Polygon):
        return [geom]
    if isinstance(geom, MultiPolygon):
        return [p for p in geom.geoms if isinstance(p, Polygon)]
    return []


def _safe_float(x):
    try:
        if x is None:
            return None
        v = float(x)
        if math.isnan(v):
            return None
        return v
    except Exception:
        return None


def _rotate_points_xy(points_xy: np.ndarray, rotate_deg: float, pivot_xy):
    """
    Rotate Nx2 points around pivot by rotate_deg degrees (CCW positive).
    """
    if points_xy is None:
        return None
    if float(rotate_deg) == 0.0:
        return points_xy
    cx = float(pivot_xy[0])
    cy = float(pivot_xy[1])
    th = math.radians(float(rotate_deg))
    c = math.cos(th)
    s = math.sin(th)

    x = points_xy[:, 0] - cx
    y = points_xy[:, 1] - cy
    xr = c * x - s * y + cx
    yr = s * x + c * y + cy
    return np.column_stack([xr, yr])


def load_dem_from_pkl(pkl_path: Path):

    """
    Load DEM data from pkl file generated by 1_buildBC_with_dem.py.
    Returns: (dem_grid, x_grid, y_grid, base_height) or None if file doesn't exist.
    """
    if not pkl_path.exists():
        return None

    try:
        with open(pkl_path, 'rb') as f:
            dem_data = pickle.load(f)

        print(f"[INFO] Loaded DEM data from pkl: {pkl_path}")
        print(f"[INFO] DEM grid shape: {dem_data['dem_grid'].shape}")
        print(f"[INFO] DEM elevation difference range: {dem_data['dem_grid'].min():.2f}m to {dem_data['dem_grid'].max():.2f}m")

        return dem_data
    except Exception as e:
        print(f"[WARN] Failed to load DEM pkl: {e}")
        return None


def convert_pkl_dem_to_points(dem_data):
    """
    Convert pkl DEM grid data to point cloud format for compatibility with existing functions.
    Returns: (points_xy, elevations) where points_xy is Nx2 array in absolute UTM coordinates and elevations is N array.
    """
    dem_grid = dem_data['dem_grid']  # (ny, nx) elevation difference array
    x_grid = dem_data['x_grid']      # 1D x coordinates (relative, 0 to x_max)
    y_grid = dem_data['y_grid']      # 1D y coordinates (relative, 0 to y_max)
    x_min = dem_data['x_min']        # Absolute UTM x minimum
    y_min = dem_data['y_min']        # Absolute UTM y minimum

    # Create meshgrid in relative coordinates
    X, Y = np.meshgrid(x_grid, y_grid, indexing='xy')

    # Convert to absolute UTM coordinates
    X_abs = X + x_min
    Y_abs = Y + y_min

    # Flatten to point cloud
    points_xy = np.column_stack([X_abs.ravel(), Y_abs.ravel()])
    elevations = dem_grid.ravel()

    # Robustness: some legacy pkls may store absolute elevations instead of diffs.
    # Normalize to datum (min=0) to match load_dem_data() behavior.
    try:
        elev_min = float(np.nanmin(elevations))
    except Exception:
        elev_min = None
    if elev_min is not None and math.isfinite(elev_min) and abs(elev_min) > 1e-6:
        elevations = elevations - elev_min
        print(f"[INFO] Adjusted PKL DEM to datum (lowest point = 0). Datum offset applied: {elev_min:.2f}m")

    print(f"[INFO] Converted DEM grid to {len(elevations)} points in absolute UTM coordinates")

    return points_xy, elevations


def load_dem_data(dem_shp_path: Path, work_crs):
    """
    Load DEM elevation data from shapefile and prepare for interpolation.
    Returns: (points_xy, elevations) where points_xy is Nx2 array and elevations is N array
    """
    print(f"[INFO] Loading DEM data from: {dem_shp_path}")
    dem_gdf = gpd.read_file(dem_shp_path)
    
    if dem_gdf.empty:
        print("[WARN] DEM shapefile is empty, will use flat terrain")
        return None, None
    
    # Force geometries to 2D before reprojection to avoid Z-coordinate issues
    print("[INFO] Ensuring DEM geometries are 2D...")
    from shapely.ops import transform
    def force_2d(geom):
        """Force geometry to 2D by dropping Z coordinates"""
        if geom is None:
            return None
        return transform(lambda x, y, z=None: (x, y), geom)

    dem_gdf['geometry'] = dem_gdf['geometry'].apply(force_2d)

    # Reproject to working CRS if needed
    if dem_gdf.crs != work_crs:
        print(f"[INFO] Reprojecting DEM from {dem_gdf.crs} to {work_crs}")
        dem_gdf = dem_gdf.to_crs(work_crs)
    
    # Extract elevation values and centroids
    elevation_col = None
    for col in ['elevation', 'Elevation', 'ELEVATION', 'height', 'Height', 'z', 'Z']:
        if col in dem_gdf.columns:
            elevation_col = col
            break
    
    if elevation_col is None:
        print("[WARN] No elevation column found in DEM, will use flat terrain")
        return None, None
    
    print(f"[INFO] Using elevation column: {elevation_col}")
    
    # Get centroids and elevations
    points = []
    elevations = []
    total_rows = len(dem_gdf)
    _PROGRESS.progress("load_dem", 0, max(total_rows, 1), f"Sampling DEM points 0/{total_rows}", force=True)
    for row_index, (_, row) in enumerate(dem_gdf.iterrows(), start=1):
        geom = row.geometry
        if geom is None or geom.is_empty:
            _PROGRESS.progress("load_dem", row_index, max(total_rows, 1), f"Sampling DEM points {row_index}/{total_rows}")
            continue
        elev = _safe_float(row[elevation_col])
        if elev is None:
            _PROGRESS.progress("load_dem", row_index, max(total_rows, 1), f"Sampling DEM points {row_index}/{total_rows}")
            continue
        
        # Use centroid as representative point
        centroid = geom.centroid
        points.append([centroid.x, centroid.y])
        elevations.append(elev)
        _PROGRESS.progress("load_dem", row_index, max(total_rows, 1), f"Sampling DEM points {row_index}/{total_rows}")
    
    if not points:
        print("[WARN] No valid DEM points found, will use flat terrain")
        return None, None
    
    points_xy = np.array(points)
    elevations = np.array(elevations)

    print(f"[INFO] Loaded {len(elevations)} DEM points")
    print(f"[INFO] Original elevation range (sea level): {elevations.min():.2f} to {elevations.max():.2f} meters")

    # Shift all elevations so minimum becomes 0 (datum adjustment)
    # This converts from sea level to relative elevation
    min_elev = elevations.min()
    elevations = elevations - min_elev

    print(f"[INFO] Adjusted to datum (lowest point = 0): {elevations.min():.2f} to {elevations.max():.2f} meters")
    print(f"[INFO] Datum offset applied: {min_elev:.2f}m")

    return points_xy, elevations


def _query_neighbor_samples(dem_points: np.ndarray, query_points: np.ndarray, n_neighbors: int):
    from scipy.spatial import cKDTree

    if dem_points is None or len(dem_points) == 0:
        raise ValueError("DEM points are required for terrain interpolation.")

    k = max(1, min(int(n_neighbors), len(dem_points)))
    tree = cKDTree(dem_points)
    distances, indices = tree.query(query_points, k=k)

    distances = np.asarray(distances, dtype=float)
    indices = np.asarray(indices, dtype=int)
    if distances.ndim == 1:
        distances = distances[:, np.newaxis]
        indices = indices[:, np.newaxis]
    return distances, indices


def _interpolate_points_idw(dem_elevations: np.ndarray, distances: np.ndarray, indices: np.ndarray, power: float) -> np.ndarray:
    distances = np.maximum(np.asarray(distances, dtype=float), 1e-10)
    weights = 1.0 / np.power(distances, float(power))
    weights_sum = weights.sum(axis=1, keepdims=True)
    weights_sum = np.where(weights_sum <= 0.0, 1.0, weights_sum)
    weights = weights / weights_sum
    return np.sum(weights * dem_elevations[indices], axis=1)


def _estimate_kriging_model(dem_points: np.ndarray, dem_elevations: np.ndarray, neighbor_distances: np.ndarray) -> tuple[float, float, float]:
    total_sill = float(np.var(dem_elevations))
    if (not math.isfinite(total_sill)) or total_sill <= 1e-12:
        elev_span = float(np.ptp(dem_elevations)) if len(dem_elevations) > 0 else 0.0
        total_sill = max((elev_span * 0.25) ** 2, 1.0)

    positive = np.asarray(neighbor_distances, dtype=float)
    positive = positive[np.isfinite(positive) & (positive > 0.0)]
    if positive.size > 0:
        range_param = float(np.median(positive) * 3.0)
    else:
        span_x = float(np.ptp(dem_points[:, 0])) if len(dem_points) > 0 else 0.0
        span_y = float(np.ptp(dem_points[:, 1])) if len(dem_points) > 0 else 0.0
        range_param = math.hypot(span_x, span_y) / 6.0
    range_param = max(range_param, 1.0)

    nugget = max(total_sill * 0.02, 1e-9)
    partial_sill = max(total_sill - nugget, 1e-9)
    return range_param, partial_sill, nugget


def _exponential_variogram(distances: np.ndarray, range_param: float, partial_sill: float, nugget: float) -> np.ndarray:
    distances = np.asarray(distances, dtype=float)
    gamma = partial_sill * (1.0 - np.exp(-np.maximum(distances, 0.0) / float(range_param)))
    return gamma + np.where(distances > 0.0, float(nugget), 0.0)


def _estimate_kriging_chunk_size(n_neighbors: int, *, target_bytes: int = 128 * 1024 * 1024) -> int:
    neighbors = max(1, int(n_neighbors))
    approx_bytes_per_query = 8 * (
        (neighbors * 2)          # local points
        + neighbors              # local elevations
        + neighbors              # local distances
        + (neighbors * neighbors) * 2
        + ((neighbors + 1) * (neighbors + 1))
        + (neighbors + 1)
        + 32
    )
    chunk = max(256, int(target_bytes // max(approx_bytes_per_query, 1)))
    return max(256, chunk)


def _estimate_kriging_gpu_chunk_size(n_neighbors: int, *, target_bytes: int = 512 * 1024 * 1024) -> int:
    neighbors = max(1, int(n_neighbors))
    approx_bytes_per_query = 4 * (
        (neighbors * 2)
        + neighbors
        + neighbors
        + 24
    )
    chunk = max(8192, int(target_bytes // max(approx_bytes_per_query, 1)))
    return max(8192, chunk)


def _estimate_idw_chunk_size(n_neighbors: int, *, target_bytes: int = 128 * 1024 * 1024) -> int:
    neighbors = max(1, int(n_neighbors))
    approx_bytes_per_query = 8 * (
        neighbors          # distances
        + neighbors        # weights
        + neighbors        # sampled elevations
        + 12
    )
    chunk = max(512, int(target_bytes // max(approx_bytes_per_query, 1)))
    return max(512, chunk)


def _emit_interpolation_progress(
    stage: str | None,
    label: str | None,
    surface_name: str,
    approach: str,
    current: int,
    total: int,
    *,
    force: bool = False,
) -> None:
    if not stage or not _PROGRESS.enabled:
        return

    if approach == "kriging_gpu":
        method_label = "ordinary kriging (GPU)"
    elif approach == "kriging":
        method_label = "ordinary kriging"
    else:
        method_label = "IDW"
    total = max(total, 1)
    _PROGRESS.progress(
        stage,
        current,
        total,
        f"Interpolating {surface_name} with {method_label} ({current}/{total} chunks)",
        label=label,
        force=force,
    )


def _interpolate_points_idw_chunked(
    dem_points: np.ndarray,
    dem_elevations: np.ndarray,
    query_points: np.ndarray,
    *,
    n_neighbors: int,
    power: float,
    progress_stage: str | None = None,
    progress_label: str | None = None,
    surface_name: str = "surface",
) -> np.ndarray:
    predictions = np.empty(len(query_points), dtype=float)
    if len(query_points) == 0:
        return predictions

    chunk_size = min(len(query_points), _estimate_idw_chunk_size(n_neighbors))
    total_chunks = max(1, math.ceil(len(query_points) / max(chunk_size, 1)))
    _emit_interpolation_progress(
        progress_stage,
        progress_label,
        surface_name,
        "idw",
        0,
        total_chunks,
        force=True,
    )

    for chunk_index, start in enumerate(range(0, len(query_points), chunk_size), start=1):
        stop = min(len(query_points), start + chunk_size)
        distances, indices = _query_neighbor_samples(dem_points, query_points[start:stop], n_neighbors)
        predictions[start:stop] = _interpolate_points_idw(dem_elevations, distances, indices, power)
        _emit_interpolation_progress(
            progress_stage,
            progress_label,
            surface_name,
            "idw",
            chunk_index,
            total_chunks,
            force=chunk_index == total_chunks,
        )

    return predictions


def _interpolate_points_kriging_rowwise(
    local_points: np.ndarray,
    local_elevations: np.ndarray,
    local_distances: np.ndarray,
    *,
    range_param: float,
    partial_sill: float,
    nugget: float,
    fallback_power: float,
) -> np.ndarray:
    from scipy.spatial.distance import cdist

    predictions = np.empty(local_points.shape[0], dtype=float)
    for row_index in range(local_points.shape[0]):
        row_points = local_points[row_index]
        row_elevations = local_elevations[row_index]
        row_distances = np.asarray(local_distances[row_index], dtype=float)

        exact_hits = np.where(row_distances <= 1e-10)[0]
        if exact_hits.size > 0:
            predictions[row_index] = float(row_elevations[exact_hits[0]])
            continue

        if row_points.shape[0] == 1 or np.allclose(row_elevations, row_elevations[0]):
            predictions[row_index] = float(row_elevations[0])
            continue

        variogram_matrix = _exponential_variogram(
            cdist(row_points, row_points),
            range_param,
            partial_sill,
            nugget,
        )
        np.fill_diagonal(variogram_matrix, 0.0)

        system_size = row_points.shape[0] + 1
        system = np.empty((system_size, system_size), dtype=float)
        system[:-1, :-1] = variogram_matrix
        system[:-1, -1] = 1.0
        system[-1, :-1] = 1.0
        system[-1, -1] = 0.0

        rhs = np.empty((system_size, 1), dtype=float)
        rhs[:-1, 0] = _exponential_variogram(row_distances, range_param, partial_sill, nugget)
        rhs[-1, 0] = 1.0

        regularization = max(float(nugget) * 1e-6, 1e-10)
        diag = np.arange(row_points.shape[0])
        system[diag, diag] += regularization

        try:
            weights = np.linalg.solve(system, rhs)[:-1, 0]
        except np.linalg.LinAlgError:
            weights = np.linalg.lstsq(system, rhs, rcond=None)[0][:-1, 0]

        prediction = float(np.dot(weights, row_elevations))
        if not math.isfinite(prediction):
            prediction = float(
                _interpolate_points_idw(
                    row_elevations,
                    row_distances[np.newaxis, :],
                    np.arange(row_points.shape[0], dtype=int)[np.newaxis, :],
                    fallback_power,
                )[0]
            )
        local_min = float(np.min(row_elevations))
        local_max = float(np.max(row_elevations))
        predictions[row_index] = min(max(prediction, local_min), local_max)

    return predictions


def _interpolate_points_kriging_chunk(
    dem_points: np.ndarray,
    dem_elevations: np.ndarray,
    distances: np.ndarray,
    indices: np.ndarray,
    *,
    range_param: float,
    partial_sill: float,
    nugget: float,
    fallback_power: float,
) -> np.ndarray:
    local_points = dem_points[indices]
    local_elevations = dem_elevations[indices]
    local_distances = np.asarray(distances, dtype=float)
    query_count, neighbor_count = local_distances.shape

    predictions = np.empty(query_count, dtype=float)
    if query_count == 0:
        return predictions

    exact_mask = np.any(local_distances <= 1e-10, axis=1)
    if np.any(exact_mask):
        exact_indices = np.argmax(local_distances <= 1e-10, axis=1)
        rows = np.nonzero(exact_mask)[0]
        predictions[rows] = local_elevations[rows, exact_indices[rows]]

    constant_mask = ~exact_mask & (
        (neighbor_count == 1) | (np.ptp(local_elevations, axis=1) <= 1e-12)
    )
    if np.any(constant_mask):
        rows = np.nonzero(constant_mask)[0]
        predictions[rows] = local_elevations[rows, 0]

    solve_mask = ~(exact_mask | constant_mask)
    if not np.any(solve_mask):
        return predictions

    pts = local_points[solve_mask]
    elev = local_elevations[solve_mask]
    dist = local_distances[solve_mask]
    active_count = pts.shape[0]

    try:
        deltas = pts[:, :, None, :] - pts[:, None, :, :]
        pairwise_distances = np.sqrt(np.sum(deltas * deltas, axis=-1))
        variogram_matrix = _exponential_variogram(
            pairwise_distances,
            range_param,
            partial_sill,
            nugget,
        )
        diag = np.arange(neighbor_count)
        variogram_matrix[:, diag, diag] = 0.0

        system = np.empty((active_count, neighbor_count + 1, neighbor_count + 1), dtype=float)
        system[:, :-1, :-1] = variogram_matrix
        system[:, :-1, -1] = 1.0
        system[:, -1, :-1] = 1.0
        system[:, -1, -1] = 0.0

        regularization = max(float(nugget) * 1e-6, 1e-10)
        system[:, diag, diag] += regularization

        rhs = np.empty((active_count, neighbor_count + 1, 1), dtype=float)
        rhs[:, :-1, 0] = _exponential_variogram(dist, range_param, partial_sill, nugget)
        rhs[:, -1, 0] = 1.0

        weights = np.linalg.solve(system, rhs)[:, :-1, 0]
        active_predictions = np.sum(weights * elev, axis=1)
    except np.linalg.LinAlgError:
        active_predictions = _interpolate_points_kriging_rowwise(
            pts,
            elev,
            dist,
            range_param=range_param,
            partial_sill=partial_sill,
            nugget=nugget,
            fallback_power=fallback_power,
        )
    else:
        invalid_mask = ~np.isfinite(active_predictions)
        if np.any(invalid_mask):
            fallback_predictions = _interpolate_points_idw(
                elev[invalid_mask],
                dist[invalid_mask],
                np.tile(np.arange(neighbor_count, dtype=int), (int(np.count_nonzero(invalid_mask)), 1)),
                fallback_power,
            )
            active_predictions[invalid_mask] = fallback_predictions

        local_min = np.min(elev, axis=1)
        local_max = np.max(elev, axis=1)
        active_predictions = np.clip(active_predictions, local_min, local_max)

    predictions[np.nonzero(solve_mask)[0]] = active_predictions
    return predictions


def _interpolate_points_kriging(
    dem_points: np.ndarray,
    dem_elevations: np.ndarray,
    query_points: np.ndarray,
    *,
    n_neighbors: int,
    fallback_power: float,
    progress_stage: str | None = None,
    progress_label: str | None = None,
    surface_name: str = "surface",
) -> np.ndarray:
    if progress_stage and _PROGRESS.enabled:
        _PROGRESS.stage(
            progress_stage,
            f"Finding neighboring DEM points for {surface_name}",
            label=progress_label,
        )
    distances, indices = _query_neighbor_samples(dem_points, query_points, n_neighbors)
    range_param, partial_sill, nugget = _estimate_kriging_model(dem_points, dem_elevations, distances)
    predictions = np.empty(len(query_points), dtype=float)
    chunk_size = min(len(query_points), _estimate_kriging_chunk_size(int(indices.shape[1])))
    if chunk_size <= 0:
        return predictions

    total_chunks = max(1, math.ceil(len(query_points) / max(chunk_size, 1)))
    _emit_interpolation_progress(
        progress_stage,
        progress_label,
        surface_name,
        "kriging",
        0,
        total_chunks,
        force=True,
    )

    for chunk_index, start in enumerate(range(0, len(query_points), chunk_size), start=1):
        stop = min(len(query_points), start + chunk_size)
        predictions[start:stop] = _interpolate_points_kriging_chunk(
            dem_points,
            dem_elevations,
            distances[start:stop],
            indices[start:stop],
            range_param=range_param,
            partial_sill=partial_sill,
            nugget=nugget,
            fallback_power=fallback_power,
        )
        _emit_interpolation_progress(
            progress_stage,
            progress_label,
            surface_name,
            "kriging",
            chunk_index,
            total_chunks,
            force=chunk_index == total_chunks,
        )

    return predictions


def _interpolate_points_kriging_gpu(
    dem_points: np.ndarray,
    dem_elevations: np.ndarray,
    query_points: np.ndarray,
    *,
    n_neighbors: int,
    fallback_power: float,
    progress_stage: str | None = None,
    progress_label: str | None = None,
    surface_name: str = "surface",
) -> np.ndarray:
    if progress_stage and _PROGRESS.enabled:
        _PROGRESS.stage(
            progress_stage,
            f"Finding neighboring DEM points for {surface_name}",
            label=progress_label,
        )
    distances, indices = _query_neighbor_samples(dem_points, query_points, n_neighbors)
    range_param, partial_sill, nugget = _estimate_kriging_model(dem_points, dem_elevations, distances)
    predictions = np.empty(len(query_points), dtype=float)
    chunk_size = min(len(query_points), _estimate_kriging_gpu_chunk_size(int(indices.shape[1])))
    if chunk_size <= 0:
        return predictions

    warmup_needed = gpu_kriging_requires_warmup()
    if warmup_needed:
        print("[INFO] CUDA kriging kernel is compiling for first use. This one-time warmup may take a little longer.")
        if progress_stage and _PROGRESS.enabled:
            _PROGRESS.stage(
                progress_stage,
                f"Compiling GPU kriging kernel for {surface_name} (first use)",
                label=progress_label,
            )
        warmup_gpu_kriging_kernel(int(indices.shape[1]))
        print("[INFO] CUDA kriging kernel warmup finished. Continuing with GPU interpolation.")

    total_chunks = max(1, math.ceil(len(query_points) / max(chunk_size, 1)))
    _emit_interpolation_progress(
        progress_stage,
        progress_label,
        surface_name,
        "kriging_gpu",
        0,
        total_chunks,
        force=True,
    )

    for chunk_index, start in enumerate(range(0, len(query_points), chunk_size), start=1):
        stop = min(len(query_points), start + chunk_size)
        local_points = dem_points[indices[start:stop]]
        local_elevations = dem_elevations[indices[start:stop]]
        predictions[start:stop] = interpolate_points_kriging_cuda_chunk(
            local_points,
            local_elevations,
            distances[start:stop],
            range_param=range_param,
            partial_sill=partial_sill,
            nugget=nugget,
            fallback_power=fallback_power,
        )
        _emit_interpolation_progress(
            progress_stage,
            progress_label,
            surface_name,
            "kriging_gpu",
            chunk_index,
            total_chunks,
            force=chunk_index == total_chunks,
        )

    return predictions


def _create_interpolated_surface(
    base_poly,
    dem_points,
    dem_elevations,
    *,
    grid_resolution: float,
    elevation_scale: float,
    smooth_sigma: float,
    smooth_sigma_factor: float,
    approach: str,
    idw_power: float,
    idw_neighbors: int,
    surface_name: str,
    progress_stage: str | None = None,
    progress_label: str | None = None,
):
    if dem_points is None or dem_elevations is None:
        return None, None, None

    print(f"[INFO] Creating {surface_name} grid (resolution: {grid_resolution}m, approach: {approach})...")

    minx, miny, maxx, maxy = base_poly.bounds
    nx = int((maxx - minx) / grid_resolution) + 1
    ny = int((maxy - miny) / grid_resolution) + 1

    x = np.linspace(minx, maxx, nx)
    y = np.linspace(miny, maxy, ny)
    X, Y = np.meshgrid(x, y)
    query_points = np.column_stack([X.ravel(), Y.ravel()])

    if approach == "kriging_gpu":
        backend = gpu_kriging_backend_summary()
        runtime_root = backend.get("runtime_root") or backend.get("cuda_home") or "auto"
        print(
            f"[INFO] Interpolating {surface_name} using GPU-accelerated ordinary kriging "
            f"with {idw_neighbors} neighboring points..."
        )
        print(f"[INFO] CUDA runtime root: {runtime_root}")
        try:
            Z = _interpolate_points_kriging_gpu(
                dem_points,
                dem_elevations,
                query_points,
                n_neighbors=idw_neighbors,
                fallback_power=idw_power,
                progress_stage=progress_stage,
                progress_label=progress_label,
                surface_name=surface_name,
            )
        except TerrainGpuKrigingUnavailable as exc:
            print(f"[WARN] GPU kriging is unavailable for {surface_name}: {exc}")
            print(f"[WARN] Falling back to CPU kriging for {surface_name}.")
            Z = _interpolate_points_kriging(
                dem_points,
                dem_elevations,
                query_points,
                n_neighbors=idw_neighbors,
                fallback_power=idw_power,
                progress_stage=progress_stage,
                progress_label=progress_label,
                surface_name=surface_name,
            )
    elif approach == "kriging":
        if len(query_points) > 50000:
            print(f"[WARN] Kriging over {len(query_points)} grid points may take noticeably longer than IDW.")
        print(f"[INFO] Interpolating {surface_name} using local ordinary kriging with {idw_neighbors} neighboring points...")
        Z = _interpolate_points_kriging(
            dem_points,
            dem_elevations,
            query_points,
            n_neighbors=idw_neighbors,
            fallback_power=idw_power,
            progress_stage=progress_stage,
            progress_label=progress_label,
            surface_name=surface_name,
        )
    else:
        print(f"[INFO] Interpolating {surface_name} using Inverse Distance Weighting (IDW) with {idw_neighbors} neighboring points...")
        if progress_stage and _PROGRESS.enabled:
            Z = _interpolate_points_idw_chunked(
                dem_points,
                dem_elevations,
                query_points,
                n_neighbors=idw_neighbors,
                power=idw_power,
                progress_stage=progress_stage,
                progress_label=progress_label,
                surface_name=surface_name,
            )
        else:
            distances, indices = _query_neighbor_samples(dem_points, query_points, idw_neighbors)
            Z = _interpolate_points_idw(dem_elevations, distances, indices, idw_power)

    Z = Z.reshape(ny, nx)

    applied_sigma = float(smooth_sigma) * float(smooth_sigma_factor)
    if applied_sigma > 0.0:
        from scipy.ndimage import gaussian_filter

        if progress_stage and _PROGRESS.enabled:
            _PROGRESS.stage(
                progress_stage,
                f"Smoothing {surface_name} (sigma={applied_sigma:.2f})",
                label=progress_label,
            )
        print(f"[INFO] Applying Gaussian smoothing to {surface_name} (sigma={applied_sigma:.2f})...")
        Z = gaussian_filter(Z, sigma=applied_sigma)
    else:
        print(f"[INFO] Smoothing disabled for {surface_name}")

    if Z.min() < 0:
        print(f"[WARN] {surface_name.capitalize()} contains negative values (min={Z.min():.2f}m), clipping to 0")
        Z = np.maximum(Z, 0.0)

    z_min_grid = float(Z.min())
    if abs(z_min_grid) > 1e-9:
        print(f"[INFO] Normalizing {surface_name} to local datum (grid min -> 0). Offset removed: {z_min_grid:.3f}m")
        Z = Z - z_min_grid
        if Z.min() < 0:
            Z = np.maximum(Z, 0.0)

    if elevation_scale != 1.0:
        print(f"[INFO] Applying elevation scale factor to {surface_name}: {elevation_scale}x")
        Z = Z * elevation_scale

    print(f"[INFO] {surface_name.capitalize()} elevation range: {Z.min():.2f} to {Z.max():.2f} meters")
    if progress_stage and _PROGRESS.enabled:
        _PROGRESS.complete(
            progress_stage,
            f"{surface_name.capitalize()} ready",
            label=progress_label,
        )
    return X, Y, Z


def create_elevation_lookup_grid(base_poly, dem_points, dem_elevations, grid_resolution=10.0, elevation_scale=1.0, smooth_sigma=1.0, approach="idw", idw_power=2.0, idw_neighbors=12):
    """
    Create a fast lookup grid for elevation queries.
    This is much faster than calling griddata() for each building.

    NOTE: dem_elevations should already be adjusted to datum (min=0)

    Args:
        base_poly: Base polygon boundary
        dem_points: Nx2 array of DEM point coordinates
        dem_elevations: N array of elevation values (already adjusted to datum)
        grid_resolution: Grid spacing in meters (smaller = more accurate but slower)
        elevation_scale: Scale factor for elevation differences
        smooth_sigma: Gaussian smoothing strength
        approach: Terrain interpolation approach ("idw", "kriging_gpu", or "kriging")
        idw_power: IDW power parameter
        idw_neighbors: Number of nearest neighbors for IDW

    Returns:
        (X, Y, Z) grid arrays for fast bilinear interpolation
    """
    if dem_points is None or dem_elevations is None:
        return None, None, None

    X, Y, Z = _create_interpolated_surface(
        base_poly,
        dem_points,
        dem_elevations,
        grid_resolution=grid_resolution,
        elevation_scale=elevation_scale,
        smooth_sigma=smooth_sigma,
        smooth_sigma_factor=0.5,
        approach=approach,
        idw_power=idw_power,
        idw_neighbors=idw_neighbors,
        surface_name="elevation lookup",
        progress_stage="terrain_lookup",
        progress_label="Preparing terrain lookup",
    )
    if X is None or Y is None or Z is None:
        return None, None, None

    nx = X.shape[1]
    ny = X.shape[0]
    print(f"[INFO] Elevation lookup grid created: {nx} x {ny} = {nx * ny} points")

    return X, Y, Z


def interpolate_elevation_fast(x, y, X_grid, Y_grid, Z_grid):
    """
    Fast elevation lookup using pre-computed grid and bilinear interpolation.

    Args:
        x, y: Query coordinates
        X_grid, Y_grid, Z_grid: Pre-computed elevation grid

    Returns:
        Interpolated elevation value
    """
    if X_grid is None or Y_grid is None or Z_grid is None:
        return 0.0

    try:
        # Get grid parameters
        ny, nx = Z_grid.shape
        x_min, x_max = X_grid[0, 0], X_grid[0, -1]
        y_min, y_max = Y_grid[0, 0], Y_grid[-1, 0]

        # Check bounds
        if x < x_min or x > x_max or y < y_min or y > y_max:
            return 0.0

        # Find grid cell
        dx = (x_max - x_min) / (nx - 1)
        dy = (y_max - y_min) / (ny - 1)

        i = int((x - x_min) / dx)
        j = int((y - y_min) / dy)

        # Clamp to valid range
        i = max(0, min(i, nx - 2))
        j = max(0, min(j, ny - 2))

        # Bilinear interpolation
        x0, x1 = X_grid[j, i], X_grid[j, i+1]
        y0, y1 = Y_grid[j, i], Y_grid[j+1, i]

        z00 = Z_grid[j, i]
        z10 = Z_grid[j, i+1]
        z01 = Z_grid[j+1, i]
        z11 = Z_grid[j+1, i+1]

        # Interpolation weights
        wx = (x - x0) / (x1 - x0) if x1 != x0 else 0.0
        wy = (y - y0) / (y1 - y0) if y1 != y0 else 0.0

        # Bilinear interpolation
        z = (1 - wx) * (1 - wy) * z00 + \
            wx * (1 - wy) * z10 + \
            (1 - wx) * wy * z01 + \
            wx * wy * z11

        return float(z)
    except Exception:
        return 0.0


def create_terrain_mesh(base_poly: Polygon, dem_points, dem_elevations, grid_resolution=50, elevation_scale=1.0, smooth_sigma=1.0, approach="idw", idw_power=2.0, idw_neighbors=12, base_height=50.0, proj_temp: Path = Path("./proj_temp")) -> trimesh.Trimesh:
    """
    Create a terrain mesh from DEM data within the base polygon.
    The terrain sits on top of the base layer (at z=base_height).

    NOTE: dem_elevations should already be adjusted so minimum = 0 (datum adjustment done in load_dem_data)

    Args:
        base_poly: Base polygon boundary
        dem_points: Nx2 array of DEM point coordinates
        dem_elevations: N array of elevation values (already adjusted to datum)
        grid_resolution: Grid spacing in meters
        elevation_scale: Scale factor for elevation differences (for visualization)
        smooth_sigma: Gaussian smoothing strength (0=no smoothing)
        approach: Terrain interpolation approach ("idw", "kriging_gpu", or "kriging")
        idw_power: IDW power parameter
        idw_neighbors: Number of nearest neighbors for IDW
        base_height: Height of base layer (terrain starts from this height)

    Returns:
        terrain_mesh: trimesh object representing the terrain surface
    """
    if dem_points is None or dem_elevations is None:
        print("[INFO] No DEM data, creating flat base")
        return None

    X, Y, Z = _create_interpolated_surface(
        base_poly,
        dem_points,
        dem_elevations,
        grid_resolution=grid_resolution,
        elevation_scale=elevation_scale,
        smooth_sigma=smooth_sigma,
        smooth_sigma_factor=1.0,
        approach=approach,
        idw_power=idw_power,
        idw_neighbors=idw_neighbors,
        surface_name="terrain mesh",
        progress_stage="terrain_mesh",
        progress_label="Creating terrain mesh",
    )
    if X is None or Y is None or Z is None:
        return None

    ny, nx = Z.shape
    print(f"[INFO] Grid size: {nx} x {ny} = {nx*ny} points")

    # Export interpolated DEM to CSV
    csv_path = proj_temp / "interpolated_dem.csv"
    print(f"[INFO] Exporting interpolated DEM to {csv_path}")
    with open(csv_path, 'w') as f:
        f.write("x,y,elevation\n")
        for i in range(ny):
            for j in range(nx):
                f.write(f"{X[i, j]:.3f},{Y[i, j]:.3f},{Z[i, j]:.3f}\n")
    print(f"[INFO] Exported {nx * ny} interpolated elevation points to {csv_path}")

    # Verify the minimum is now ~0
    actual_min = Z.min()
    if abs(actual_min) > 0.01:
        print(f"[WARN] Minimum elevation is {actual_min:.2f}m, expected ~0.00m")

    # Create a solid terrain mesh (from base_height to terrain surface)
    # This sits on top of the base layer

    # Create top surface vertices (terrain surface on top of base layer)
    vertices_top = []
    for i in range(ny):
        for j in range(nx):
            vertices_top.append([X[i, j], Y[i, j], base_height + Z[i, j]])

    # Create bottom surface vertices (at base_height, top of base layer)
    vertices_bottom = []
    for i in range(ny):
        for j in range(nx):
            vertices_bottom.append([X[i, j], Y[i, j], base_height])

    vertices = np.vstack([vertices_top, vertices_bottom])

    # Create faces
    faces = []
    n_top = ny * nx

    # Top surface triangles
    for i in range(ny - 1):
        for j in range(nx - 1):
            v0 = i * nx + j
            v1 = i * nx + (j + 1)
            v2 = (i + 1) * nx + j
            v3 = (i + 1) * nx + (j + 1)

            faces.append([v0, v1, v2])
            faces.append([v1, v3, v2])

    # Bottom surface triangles (reversed winding)
    for i in range(ny - 1):
        for j in range(nx - 1):
            v0 = n_top + i * nx + j
            v1 = n_top + i * nx + (j + 1)
            v2 = n_top + (i + 1) * nx + j
            v3 = n_top + (i + 1) * nx + (j + 1)

            faces.append([v0, v2, v1])
            faces.append([v1, v2, v3])

    # Side faces (connect top and bottom edges)
    # Left edge (j=0)
    for i in range(ny - 1):
        v0_top = i * nx
        v1_top = (i + 1) * nx
        v0_bot = n_top + i * nx
        v1_bot = n_top + (i + 1) * nx
        faces.append([v0_top, v1_top, v0_bot])
        faces.append([v1_top, v1_bot, v0_bot])

    # Right edge (j=nx-1)
    for i in range(ny - 1):
        v0_top = i * nx + (nx - 1)
        v1_top = (i + 1) * nx + (nx - 1)
        v0_bot = n_top + i * nx + (nx - 1)
        v1_bot = n_top + (i + 1) * nx + (nx - 1)
        faces.append([v0_top, v0_bot, v1_top])
        faces.append([v1_top, v0_bot, v1_bot])

    # Front edge (i=0)
    for j in range(nx - 1):
        v0_top = j
        v1_top = j + 1
        v0_bot = n_top + j
        v1_bot = n_top + j + 1
        faces.append([v0_top, v0_bot, v1_top])
        faces.append([v1_top, v0_bot, v1_bot])

    # Back edge (i=ny-1)
    for j in range(nx - 1):
        v0_top = (ny - 1) * nx + j
        v1_top = (ny - 1) * nx + j + 1
        v0_bot = n_top + (ny - 1) * nx + j
        v1_bot = n_top + (ny - 1) * nx + j + 1
        faces.append([v0_top, v1_top, v0_bot])
        faces.append([v1_top, v1_bot, v0_bot])

    faces = np.array(faces)

    terrain_mesh = trimesh.Trimesh(vertices=vertices, faces=faces)

    print(f"[INFO] Terrain mesh created: {len(vertices)} vertices, {len(faces)} faces")
    print(f"[INFO] Terrain is a solid volume from z={base_height}m to terrain surface")

    return terrain_mesh

def extrude_polygon_to_mesh(poly: Polygon, height: float) -> trimesh.Trimesh:
    def _ensure_2d_coords(coords):
        """Ensure coordinates are 2D"""
        return [(x, y) for x, y, *_ in coords] if len(coords[0]) > 2 else coords

    exterior_coords = list(poly.exterior.coords)
    exterior_2d = _ensure_2d_coords(exterior_coords)

    holes_2d = []
    for interior in poly.interiors:
        interior_coords = list(interior.coords)
        interior_2d = _ensure_2d_coords(interior_coords)
        holes_2d.append(interior_2d)

    if holes_2d:
        poly_2d = Polygon(exterior_2d, holes_2d)
    else:
        poly_2d = Polygon(exterior_2d)

    try:
        mesh = trimesh.creation.extrude_polygon(poly_2d, height, engine="earcut")
    except Exception:
        try:
            mesh = trimesh.creation.extrude_polygon(poly_2d, height, engine="triangle")
        except Exception as e:
            raise RuntimeError("No triangulation engine available, please install mapbox_earcut or triangle") from e

    return mesh

def _build_bbox_polygon_from_conf(conf_path) -> Polygon:
    """
    Parse conf file to extract cut_lon_manual and cut_lat_manual to create bounding box polygon.
    """
    conf_file = Path(conf_path).expanduser().resolve()
    if not conf_file.exists():
        raise FileNotFoundError(f"[ERROR] Configuration file not found: {conf_file}")
    deck = load_deck(conf_file)
    lon_pair = deck.get_pair("cut_lon_manual")
    lat_pair = deck.get_pair("cut_lat_manual")
    if lon_pair is None or lat_pair is None:
        raise ValueError("conf 中未找到 cut_lon_manual/cut_lat_manual")
    minx, maxx = lon_pair
    miny, maxy = lat_pair

    ring = [(minx, miny), (maxx, miny), (maxx, maxy), (minx, maxy), (minx, miny)]
    return Polygon(ring)


def _project_geometry(geom: Polygon, target_crs) -> Polygon:
    """
    Project geometry to target CRS using GeoSeries's to_crs.
    """
    gs = gpd.GeoSeries([geom], crs="EPSG:4326")
    gs2 = gs.to_crs(target_crs)
    result = gs2.iloc[0]
    if isinstance(result, Polygon):
        return result
    else:
        raise RuntimeError(f"投影结果不是Polygon类型: {type(result)}")

def _init_worker(elev_data):
    """
    Initialize global elevation data in worker process.
    """
    global X_ELEV_GRID, Y_ELEV_GRID, Z_ELEV_GRID, BASE_HEIGHT_FOR_BUILDING
    X_ELEV_GRID, Y_ELEV_GRID, Z_ELEV_GRID, BASE_HEIGHT_FOR_BUILDING = elev_data


def _build_one_proc(task):
    """
    Build one building mesh in worker process.
    """
    idx, poly, h = task
    if h <= 0:
        return idx, None, None, None
    try:
        terrain_elevs = []
        for coord in poly.exterior.coords:
            x, y = coord[0], coord[1]
            elev = interpolate_elevation_fast(
                x, y,
                X_ELEV_GRID, Y_ELEV_GRID, Z_ELEV_GRID
            )
            terrain_elevs.append(elev)
        min_terrain_elev = min(terrain_elevs) if terrain_elevs else 0.0
        base_elev = BASE_HEIGHT_FOR_BUILDING + min_terrain_elev
        m = extrude_polygon_to_mesh(poly, h)
        m.apply_translation([0.0, 0.0, base_elev])
        return idx, m, base_elev, None
    except Exception as e:
        return idx, None, None, e
    
def _poly_from_raw(raw):
    exterior, holes = raw
    if holes:
        return Polygon(exterior, holes)
    else:
        return Polygon(exterior)

def _build_batch_from_raw(batch):
    results = []
    for idx, raw_poly, h in batch:
        poly = _poly_from_raw(raw_poly)
        results.append(_build_one_proc((idx, poly, h)))
    return results

def _build_batch_proc(tasks_batch):
    results = []
    for t in tasks_batch:
        results.append(_build_one_proc(t))
    return results

def main():
    program_start_time = time.time()
    parser = argparse.ArgumentParser(
        description="Voxelization of buildings with terrain-aware base elevation"
    )
    parser.add_argument(
        "conf",
        help="path to deck file"
    )
    parser.add_argument(
        "--height-field",
        default=None,
        help="height field in shapefile, or 'Inferred' (legacy 'auto') to detect (Height, Elevation, etc.). "
             "If omitted, deck key terr_voxel_height_field is used before falling back to 'Inferred'."
    )
    parser.add_argument(
        "--min-height",
        type=float,
        default=None,
        help="minimum valid height in meters. Buildings with height less than or equal to this will be ignored. "
             "If omitted, deck key terr_voxel_ignore_under is used before falling back to 0.0."
    )
    parser.add_argument(
        "--no-reproject",
        action="store_true",
        help="do not reproject shapefile to UTM, use original CRS"
    )
    parser.add_argument(
        "--dem-path",
        type=str,
        default=None,
        help="path to DEM shapefile. If not provided, will look for DEM folder in project home"
    )
    parser.add_argument(
        "--dem-source",
        type=str,
        choices=("auto", "shp", "pkl"),
        default="auto",
        help="DEM source selection. auto=prefer shapefile/GeoTIFF then fallback to PKL. Default: auto"
    )
    parser.add_argument(
        "--terrain-resolution",
        type=float,
        default=None,
        help="terrain interpolation grid resolution in meters. "
             "If omitted, deck key terr_voxel_grid_resolution is used before falling back to 50.0."
    )
    parser.add_argument(
        "--max-buildings",
        type=int,
        default=None,
        help="maximum number of buildings to process (for testing). Default: process all buildings"
    )
    parser.add_argument(
        "--elevation-scale",
        type=float,
        default=1.0,
        help="scale factor for elevation differences (for visualization/testing). Default: 1.0"
    )
    parser.add_argument(
        "--smooth-sigma",
        type=float,
        default=None,
        help="Gaussian smoothing strength for terrain interpolation (0=no smoothing). "
             "If omitted, deck key terr_voxel_idw_sigma is used before falling back to 1.0."
    )
    parser.add_argument(
        "--idw-power",
        type=float,
        default=None,
        help="IDW power parameter (higher = more weight to closer points, 1-3 recommended). "
             "If omitted, deck key terr_voxel_idw_power is used before falling back to 2.0."
    )
    parser.add_argument(
        "--idw-neighbors",
        type=int,
        default=None,
        help="Number of nearest neighbors for terrain interpolation. "
             "If omitted, deck key terr_voxel_idw_neighbors is used before falling back to 12."
    )
    parser.add_argument(
        "--terrain-approach",
        type=str,
        choices=ALLOWED_TERR_VOXEL_APPROACHES,
        default=None,
        help="terrain interpolation approach. If omitted, deck key terr_voxel_approach is used before falling back to idw."
    )
    parser.add_argument(
        "--base-height",
        type=float,
        default=None,
        help="Base layer height in meters (terrain sits on top of this). If not set, will read base_height from conf (fallback 50.0)."
    )

    args = parser.parse_args()
    print("[INFO] Parsed CLI arguments")
    _PROGRESS.stage("load_shapefile", "Loading cropped building geometries")

    conf_file = Path(args.conf).expanduser().resolve()
    if not conf_file.exists():
        raise FileNotFoundError(f"conf file not found: {conf_file}")
    project_home = conf_file.parent
    proj_temp = project_home / "proj_temp"
    proj_temp.mkdir(parents=True, exist_ok=True)

    txt_conf = conf_file.read_text(encoding="utf-8", errors="ignore")
    deck = load_deck(conf_file)
    case_name = deck.get_text("casename")
    if not case_name:
        raise RuntimeError("casename not found in conf")

    terr_voxel_cfg, terr_voxel_sources = resolve_terrain_voxel_config(
        deck,
        cli_overrides={
            "approach": args.terrain_approach,
            "height_field": args.height_field,
            "ignore_under": args.min_height,
            "grid_resolution": args.terrain_resolution,
            "idw_sigma": args.smooth_sigma,
            "idw_power": args.idw_power,
            "idw_neighbors": args.idw_neighbors,
        },
        warn=lambda message: print(f"[WARN] {message}"),
    )
    args.terrain_approach = terr_voxel_cfg.approach
    args.height_field = terr_voxel_cfg.height_field
    args.min_height = terr_voxel_cfg.ignore_under
    args.terrain_resolution = terr_voxel_cfg.grid_resolution
    args.smooth_sigma = terr_voxel_cfg.idw_sigma
    args.idw_power = terr_voxel_cfg.idw_power
    args.idw_neighbors = terr_voxel_cfg.idw_neighbors

    # If --base-height is not provided, read from conf (same behavior as 1_buildBC.py)
    if args.base_height is None:
        conf_base_height = deck.get_float("base_height")
        args.base_height = conf_base_height if conf_base_height is not None else 50.0
    if (not math.isfinite(float(args.base_height))) or (float(args.base_height) < 0.0):
        args.base_height = 50.0
    print(f"[INFO] Base height: {args.base_height} m")

    try:
        utm_crs = get_utm_crs_from_conf_raw(txt_conf, default_epsg=None)
    except Exception as e:
        raise RuntimeError(f"[ERROR] Failed to determine UTM CRS from conf (cut_lon_manual/cut_lat_manual): {e}")
    print(f"[INFO] UTM CRS for CFD domain: {utm_crs}")


    # Find building shapefile
    primary_shp = proj_temp / f"cutted_shp/{case_name}.shp"
    fallback_shp = proj_temp / f"{case_name}.shp"

    if primary_shp.exists():
        shp_path = primary_shp
    elif fallback_shp.exists():
        print(f"[WARN] Primary shapefile not found: {primary_shp.name}. Fallback to {fallback_shp.name}")
        shp_path = fallback_shp
    else:
        raise FileNotFoundError(f"Shapefile not found: {primary_shp} or {fallback_shp}")

    print(f"[INFO] Input Shapefile: {shp_path}")
    print(f"[INFO] Terrain approach: {args.terrain_approach} (source: {terr_voxel_sources['approach']})")
    height_field_display = "Inferred" if str(args.height_field).strip().lower() == "auto" else args.height_field
    print(f"[INFO] Height field: {height_field_display} (source: {terr_voxel_sources['height_field']})")
    print(f"[INFO] Min valid height: {args.min_height} m (source: {terr_voxel_sources['ignore_under']})")
    print(f"[INFO] Terrain grid resolution: {args.terrain_resolution} m (source: {terr_voxel_sources['grid_resolution']})")
    print(f"[INFO] Terrain smoothing sigma: {args.smooth_sigma} (source: {terr_voxel_sources['idw_sigma']})")
    print(f"[INFO] IDW power: {args.idw_power} (source: {terr_voxel_sources['idw_power']})")
    print(f"[INFO] Neighboring points: {args.idw_neighbors} (source: {terr_voxel_sources['idw_neighbors']})")

    combined_file = proj_temp / f"{case_name}.stl"

    print(f"[INFO] Reading features from file")
    gdf = gpd.read_file(shp_path)
    if len(gdf) == 0:
        raise RuntimeError("Shapefile has no features")
    print(f"[INFO] Read {len(gdf)} features")
    print(f"[INFO] Source CRS: {gdf.crs}")

    if gdf.crs is None:
        gdf = gdf.set_crs("EPSG:4326", allow_override=True)

    # Use UTM CRS determined from configuration
    gdf_work = gdf.copy()
    if not args.no_reproject:
        try:
            gdf_work = gdf_work.to_crs(utm_crs)
        except Exception as e:
            raise RuntimeError(f"[ERROR] Failed to reproject buildings to {utm_crs}: {e}")

    work_crs = gdf_work.crs
    print(f"[INFO] Working CRS for CFD domain: {work_crs}")


    # DEM loading strategy (prefer SHP/GeoTIFF by default; PKL is typically coarser and may cause blocky terrain)
    proj_temp = project_home / "proj_temp"
    dem_pkl_path = proj_temp / "dem_grid.pkl"

    dem_points, dem_elevations = None, None
    dem_data_pkl = None
    use_pkl_dem = False

    def _try_load_dem_shp() -> tuple[np.ndarray | None, np.ndarray | None]:
        if args.dem_path:
            dem_path = Path(args.dem_path)
            print(f"[INFO] Using user-provided DEM shapefile: {dem_path}")
        else:
            dem_path = None
            for folder_name in ("terrain_db", "DEM"):
                dem_folder = project_home / folder_name
                if dem_folder.exists():
                    dem_files = sorted(dem_folder.glob("*.shp"))
                    if dem_files:
                        dem_path = dem_files[0]
                        print(f"[INFO] Auto-detected DEM file: {dem_path}")
                        break
                    else:
                        print(f"[WARN] No DEM shapefile found in {folder_name} folder")
        if dem_path and dem_path.exists():
            return load_dem_data(dem_path, work_crs)
        print("[INFO] No DEM shapefile found. Trying GeoTIFF fallback...")
        created = ensure_dem_shp_from_tif(txt_conf, project_home)
        if created and created.exists():
            return load_dem_data(created, work_crs)
        return None, None

    def _try_load_dem_pkl() -> tuple[np.ndarray | None, np.ndarray | None, dict | None]:
        pkl_data = load_dem_from_pkl(dem_pkl_path)
        if pkl_data is None:
            return None, None, None
        pts, elevs = convert_pkl_dem_to_points(pkl_data)
        return pts, elevs, pkl_data

    if args.dem_source in ("auto", "shp"):
        _PROGRESS.stage("load_dem", "Loading terrain DEM")
        print("[INFO] Loading DEM from shapefile/GeoTIFF ...")
        dem_points, dem_elevations = _try_load_dem_shp()

    if dem_points is None and args.dem_source in ("auto", "pkl", "shp"):
        if args.dem_source == "shp":
            print("[WARN] DEM shapefile/GeoTIFF not available. Falling back to PKL if present.")
        _PROGRESS.stage("load_dem", "Loading cached terrain DEM")
        print("[INFO] Loading DEM from PKL ...")
        dem_points, dem_elevations, dem_data_pkl = _try_load_dem_pkl()
        use_pkl_dem = dem_data_pkl is not None and dem_points is not None and dem_elevations is not None
        if use_pkl_dem:
            print("[INFO] Using DEM data from pkl file (dem_grid.pkl)")
            try:
                pkl_base_height = _safe_float(dem_data_pkl.get("base_height"))
            except Exception:
                pkl_base_height = None
            if pkl_base_height is not None and abs(float(pkl_base_height) - float(args.base_height)) > 1e-6:
                print(
                    f"[WARN] PKL base_height={float(pkl_base_height):.3f}m differs from current base_height={float(args.base_height):.3f}m. "
                    f"STL will use base_height={float(args.base_height):.3f}m."
                )

    if dem_points is None:
        print("[INFO] No DEM data available, will create flat terrain")

    # Auto-detect height field
    if str(args.height_field).strip().lower() in {"auto", "inferred"}:
        height_candidates = ["Height", "Elevation", "height", "elevation", "HEIGHT", "ELEVATION"]
        height_field = None
        for candidate in height_candidates:
            if candidate in gdf_work.columns:
                height_field = candidate
                print(f"[INFO] Auto-detected height field: {height_field}")
                break
        if height_field is None:
            raise RuntimeError(f"Cannot auto-detect height field. Available fields: {list(gdf_work.columns)}")
        args.height_field = height_field
    else:
        if args.height_field not in gdf_work.columns:
            raise RuntimeError(
                f"Specified height field '{args.height_field}' not found. Available fields: {list(gdf_work.columns)}"
            )
        print(f"[INFO] Using specified height field: {args.height_field}")

    # Build bbox - project only two corner points (same as 1_buildBC.py)
    conf_file_path = Path(conf_file).expanduser().resolve()
    if not conf_file_path.exists():
        raise FileNotFoundError(f"[ERROR] Configuration file not found: {conf_file_path}")
    conf_deck = load_deck(conf_file_path)
    lon_pair = conf_deck.get_pair("cut_lon_manual")
    lat_pair = conf_deck.get_pair("cut_lat_manual")
    if lon_pair is None or lat_pair is None:
        raise ValueError("conf 中未找到 cut_lon_manual/cut_lat_manual")
    lon_min, lon_max = lon_pair
    lat_min, lat_max = lat_pair

    print(f"[INFO] Config bounds: lon=[{lon_min}, {lon_max}], lat=[{lat_min}, {lat_max}]")

    # Project four corner points to UTM (consistent with buildBC rotation logic)
    from pyproj import Transformer
    transformer = Transformer.from_crs("EPSG:4326", work_crs, always_xy=True)
    x00, y00 = transformer.transform(lon_min, lat_min)
    x10, y10 = transformer.transform(lon_max, lat_min)
    x11, y11 = transformer.transform(lon_max, lat_max)
    x01, y01 = transformer.transform(lon_min, lat_max)

    # Read rotate_deg from conf when present; otherwise compute from lower edge
    rotate_deg_conf = conf_deck.get_float("rotate_deg")
    if rotate_deg_conf is None:
        dx0 = x10 - x00
        dy0 = y10 - y00
        angle_rad = math.atan2(dy0, dx0)
        rotate_deg_conf = -math.degrees(angle_rad)

    pivot_xy_conf = (
        (x00 + x10 + x11 + x01) / 4.0,
        (y00 + y10 + y11 + y01) / 4.0,
    )

    corners = np.array([[x00, y00], [x10, y10], [x11, y11], [x01, y01]], dtype=float)
    corners_rot = _rotate_points_xy(corners, rotate_deg_conf, pivot_xy_conf)

    x_min_conf = float(corners_rot[:, 0].min())
    x_max_conf = float(corners_rot[:, 0].max())
    y_min_conf = float(corners_rot[:, 1].min())
    y_max_conf = float(corners_rot[:, 1].max())

    print(
        f"[INFO] Projected corners (UTM): "
        f"({x00:.3f},{y00:.3f}) ({x10:.3f},{y10:.3f}) ({x11:.3f},{y11:.3f}) ({x01:.3f},{y01:.3f})"
    )
    print(f"[INFO] Rotation from conf/config: rotate_deg={rotate_deg_conf:.6f}, pivot=({pivot_xy_conf[0]:.3f}, {pivot_xy_conf[1]:.3f})")
    print(f"[INFO] Domain size in rotated frame: {x_max_conf - x_min_conf:.3f} x {y_max_conf - y_min_conf:.3f} m")

    # Build boundary box and rotation
    if use_pkl_dem and dem_data_pkl is not None:
        x_min_pkl = float(dem_data_pkl["x_min"])
        y_min_pkl = float(dem_data_pkl["y_min"])

        x_grid_pkl = np.asarray(dem_data_pkl["x_grid"])
        y_grid_pkl = np.asarray(dem_data_pkl["y_grid"])

        minx = x_min_pkl
        miny = y_min_pkl
        maxx = x_min_pkl + float(x_grid_pkl.max())
        maxy = y_min_pkl + float(y_grid_pkl.max())

        rotate_deg = float(dem_data_pkl.get("rotate_deg", 0.0))
        pivot_xy_raw = dem_data_pkl.get("pivot_xy", ((minx + maxx) / 2, (miny + maxy) / 2))
        pivot_xy = (float(pivot_xy_raw[0]), float(pivot_xy_raw[1]))

        base_rot = Polygon([(minx, miny), (maxx, miny), (maxx, maxy), (minx, maxy)])
        print(f"[INFO] Using pkl DEM bounds: x=[{minx:.3f}, {maxx:.3f}], y=[{miny:.3f}, {maxy:.3f}]")
        print(f"[INFO] Using pkl rotation: rotate_deg={rotate_deg:.6f}, pivot=({pivot_xy[0]:.3f}, {pivot_xy[1]:.3f})")
    else:
        minx, miny, maxx, maxy = x_min_conf, y_min_conf, x_max_conf, y_max_conf
        base_rot = Polygon([(minx, miny), (maxx, miny), (maxx, maxy), (minx, maxy)])
        rotate_deg = rotate_deg_conf
        pivot_xy = (float(pivot_xy_conf[0]), float(pivot_xy_conf[1]))
        print("[INFO] Using config-rotated bounding box (match buildBC CSV frame)")
    # Rotate DEM points into the same rotated frame when DEM is not from pkl
    if (dem_points is not None) and (not use_pkl_dem) and (rotate_deg != 0.0):
        dem_points = _rotate_points_xy(dem_points, rotate_deg, pivot_xy)

    # Filter buildings by height (no rotation needed)
    _PROGRESS.stage("filter_buildings", "Filtering buildings by height")
    print("[INFO] Filtering building polygons by height")
    rotated_polygons = []
    heights = []
    total_rows = len(gdf_work)
    _PROGRESS.progress("filter_buildings", 0, max(total_rows, 1), f"Filtering buildings 0/{total_rows}", force=True)
    for index, (_, row) in enumerate(gdf_work.iterrows(), start=1):
        geom = row.geometry
        if geom is None or geom.is_empty:
            _PROGRESS.progress("filter_buildings", index, max(total_rows, 1), f"Filtering buildings {index}/{total_rows}")
            continue
        h = _safe_float(row.get(args.height_field))
        if h is None or h <= args.min_height:
            _PROGRESS.progress("filter_buildings", index, max(total_rows, 1), f"Filtering buildings {index}/{total_rows}")
            continue
        geom_valid = _make_valid(geom)
        if geom_valid is None or geom_valid.is_empty:
            _PROGRESS.progress("filter_buildings", index, max(total_rows, 1), f"Filtering buildings {index}/{total_rows}")
            continue
        polys = _to_iter_polygons(geom_valid)
        if not polys:
            _PROGRESS.progress("filter_buildings", index, max(total_rows, 1), f"Filtering buildings {index}/{total_rows}")
            continue
        for poly in polys:
            try:
                if rotate_deg != 0.0:
                    poly_use = affinity.rotate(poly, rotate_deg, origin=pivot_xy, use_radians=False)
                else:
                    poly_use = poly
                rotated_polygons.append(poly_use)
                heights.append(h)
            except Exception:
                continue
        _PROGRESS.progress("filter_buildings", index, max(total_rows, 1), f"Filtering buildings {index}/{total_rows}")


    if not rotated_polygons:
        raise RuntimeError("[ERROR] No valid building polygons available")

    # Clip buildings to boundary
    _PROGRESS.stage("clip_buildings", "Clipping buildings to CFD domain")
    print("[INFO] Clipping buildings to boundary box")
    clipped_polygons = []
    clipped_heights = []
    boundary_box = base_rot

    total_clips = len(rotated_polygons)
    _PROGRESS.progress("clip_buildings", 0, max(total_clips, 1), f"Clipping polygons 0/{total_clips}", force=True)
    for index, (poly, h) in enumerate(zip(rotated_polygons, heights), start=1):
        try:
            clipped = poly.intersection(boundary_box)
            if not clipped.is_empty and clipped.area > 0:
                if isinstance(clipped, Polygon):
                    clipped_polygons.append(clipped)
                    clipped_heights.append(h)
                elif isinstance(clipped, MultiPolygon):
                    for sub_poly in clipped.geoms:
                        if isinstance(sub_poly, Polygon) and sub_poly.area > 0:
                            clipped_polygons.append(sub_poly)
                            clipped_heights.append(h)
        except Exception:
            continue
        _PROGRESS.progress("clip_buildings", index, max(total_clips, 1), f"Clipping polygons {index}/{total_clips}")

    rotated_polygons = clipped_polygons
    heights = clipped_heights
    print(f"[INFO] Clipped buildings: {len(rotated_polygons)} polygons remaining")

    if heights:
        print(f"[INFO] Building height stats: min {min(heights):.3f}m, max {max(heights):.3f}m")

    # Limit number of buildings if specified (for testing)
    if args.max_buildings is not None and len(rotated_polygons) > args.max_buildings:
        print(f"[INFO] Limiting to first {args.max_buildings} buildings (--max-buildings parameter)")
        rotated_polygons = rotated_polygons[:args.max_buildings]
        heights = heights[:args.max_buildings]

    # Calculate translation to origin
    minx_all, miny_all = base_rot.bounds[0], base_rot.bounds[1]
    tx, ty = -minx_all, -miny_all

    base_final = affinity.translate(base_rot, xoff=tx, yoff=ty)
    print(f"[INFO] Translation offsets: dx {tx:.3f}, dy {ty:.3f}")

    shifted_polygons = [affinity.translate(p, xoff=tx, yoff=ty) for p in rotated_polygons]

    # Translate DEM points
    if dem_points is not None:
        dem_points[:, 0] += tx
        dem_points[:, 1] += ty

    # Create base layer (z=0 to z=base_height)
    _PROGRESS.stage("create_base", f"Creating base layer to {args.base_height:.2f} m")
    print(f"[INFO] Creating base layer from z=0 to z={args.base_height}m")
    base_mesh = extrude_polygon_to_mesh(base_final, args.base_height)
    print("[INFO] Base layer created")

    # Create terrain mesh (sits on top of base layer)
    _PROGRESS.stage("terrain_mesh", "Creating terrain mesh")
    terrain_mesh = create_terrain_mesh(
        base_final,
        dem_points,
        dem_elevations,
        args.terrain_resolution,
        elevation_scale=args.elevation_scale,
        smooth_sigma=args.smooth_sigma,
        approach=args.terrain_approach,
        idw_power=args.idw_power,
        idw_neighbors=args.idw_neighbors,
        base_height=args.base_height,
        proj_temp=proj_temp
    )
    
    dem_used = terrain_mesh is not None
    if dem_used:
        combined_file = proj_temp / f"{case_name}_DEM.stl"
    else:
        combined_file = proj_temp / f"{case_name}.stl"
    print(f"[INFO] Combined STL output path: {combined_file}")
    # Create fast elevation lookup grid for building placement
    # Note: dem_elevations are already adjusted to datum (min=0)
    _PROGRESS.stage("terrain_lookup", "Preparing terrain lookup grid")
    X_elev_grid, Y_elev_grid, Z_elev_grid = create_elevation_lookup_grid(
        base_final,
        dem_points,
        dem_elevations,
        grid_resolution=args.terrain_resolution,
        elevation_scale=args.elevation_scale,
        smooth_sigma=args.smooth_sigma,
        approach=args.terrain_approach,
        idw_power=args.idw_power,
        idw_neighbors=args.idw_neighbors
    )

    # Report terrain statistics
    if terrain_mesh is not None:
        min_terrain_z = terrain_mesh.vertices[:, 2].min()
        max_terrain_z = terrain_mesh.vertices[:, 2].max()
        print(f"[INFO] Terrain layer elevation range: {min_terrain_z:.2f}m to {max_terrain_z:.2f}m")
        print(f"[INFO] Terrain relief: {max_terrain_z - min_terrain_z:.2f}m")

    # Generate building meshes
    building_meshes = []
    failed_count = 0
    building_base_elevations = []

    total_buildings = len(shifted_polygons)
    extrude_start_time = time.time()
    _PROGRESS.progress("voxelize", 0, max(total_buildings, 1), f"Extruding buildings 0/{total_buildings}", force=True)
    print(f"[INFO] Extruding {total_buildings} buildings in parallel...")


    raw_polys = []
    for poly in shifted_polygons:
        ext = [(x, y) for x, y, *rest in poly.exterior.coords]
        holes = []
        for ring in poly.interiors:
            holes.append([(x, y) for x, y, *rest in ring.coords])
        raw_polys.append((ext, holes))

    import random

    tasks = [(i, raw_polys[i], heights[i]) for i in range(len(raw_polys))]
    random.shuffle(tasks)

    max_workers = min(64, os.cpu_count() or 1)
    print(f"[INFO] Using up to {max_workers} parallel workers")
    batch_size = 500

    task_batches = [tasks[i:i + batch_size] for i in range(0, len(tasks), batch_size)]

    if not _PROGRESS.enabled:
        sys.stdout.write(f"[INFO] Using {len(task_batches)} batches for {batch_size} parallel tasks |")
        sys.stdout.flush()


    max_workers = min(32, os.cpu_count() or 1)

    results = [None] * len(tasks)

    nz = len(tasks)
    next_percent_idx = 1
    completed = 0

    elev_data = (X_elev_grid, Y_elev_grid, Z_elev_grid, args.base_height)

    with concurrent.futures.ProcessPoolExecutor(
        max_workers=max_workers,
        initializer=_init_worker,
        initargs=(elev_data,)
    ) as executor:
        future_to_batch = {}
        for batch in task_batches:
            fut = executor.submit(_build_batch_from_raw, batch)
            future_to_batch[fut] = batch

            done_now = [f for f in list(future_to_batch) if f.done()]
            for future in done_now:
                batch_res = future.result()
                for res in batch_res:
                    idx, m, base_elev, err = res
                    results[idx] = res

                    completed += 1
                    _PROGRESS.progress("voxelize", completed, max(nz, 1), f"Extruding buildings {completed}/{nz}")
                    if not _PROGRESS.enabled:
                        progress_ratio = completed / nz if nz > 0 else 1.0
                        while next_percent_idx <= 20 and progress_ratio >= (next_percent_idx / 20.0):
                            sys.stdout.write("#")
                            if next_percent_idx % 4 == 0:
                                sys.stdout.write(f"|{next_percent_idx * 5}%|")
                            sys.stdout.flush()
                            next_percent_idx += 1
                del future_to_batch[future]

        for future in concurrent.futures.as_completed(list(future_to_batch)):
            batch_res = future.result()
            for res in batch_res:
                idx, m, base_elev, err = res
                results[idx] = res

                completed += 1
                _PROGRESS.progress("voxelize", completed, max(nz, 1), f"Extruding buildings {completed}/{nz}")
                if not _PROGRESS.enabled:
                    progress_ratio = completed / nz if nz > 0 else 1.0
                    while next_percent_idx <= 20 and progress_ratio >= (next_percent_idx / 20.0):
                        sys.stdout.write("#")
                        if next_percent_idx % 4 == 0:
                            sys.stdout.write(f"|{next_percent_idx * 5}%|")
                        sys.stdout.flush()
                        next_percent_idx += 1

        if not _PROGRESS.enabled:
            sys.stdout.flush()

    if not _PROGRESS.enabled:
        sys.stdout.write("|Finished|\n")
        sys.stdout.flush()

    for idx, m, base_elev, err in results:
        if err is not None:
            failed_count += 1
            if failed_count <= 5:
                print(f"[WARN] Building {idx} extrusion failed: {err}")
            continue
        building_meshes.append(m)
        building_base_elevations.append(base_elev)

    extrude_elapsed = time.time() - extrude_start_time
    print(f"[INFO] Extruding all buildings took {extrude_elapsed:.2f} seconds")

    if failed_count > 0:
        print(f"[WARN] Total {failed_count} buildings failed to extrude")

    print(f"[INFO] Extruded {len(building_meshes)} building meshes")


    if building_base_elevations:
        base_elev_array = np.array(building_base_elevations)
        print(f"[INFO] Building base elevation stats:")
        print(f"       Min: {base_elev_array.min():.2f}m, Max: {base_elev_array.max():.2f}m")
        print(f"       Mean: {base_elev_array.mean():.2f}m, Std: {base_elev_array.std():.2f}m")

    # Combine all layers: base + terrain + buildings
    meshes_to_combine = [base_mesh]
    if terrain_mesh is not None:
        meshes_to_combine.append(terrain_mesh)
    if building_meshes:
        meshes_to_combine.extend(building_meshes)

    if len(meshes_to_combine) == 1:
        print("[INFO] Only base layer, no terrain or buildings")
        final_mesh = base_mesh
    else:
        try:
            layer_names = ["base"]
            if terrain_mesh is not None:
                layer_names.append("terrain")
            if building_meshes:
                layer_names.append(f"{len(building_meshes)} buildings")
            print(f"[INFO] Combining layers: {', '.join(layer_names)}")
            final_mesh = trimesh.util.concatenate(meshes_to_combine)
            print("[INFO] Mesh combination succeeded")
        except Exception as e:
            print(f"[WARN] Mesh combination failed: {e}")
            final_mesh = trimesh.util.concatenate(meshes_to_combine)

    _PROGRESS.stage("save_stl", f"Saving STL: {combined_file.name}")
    final_mesh.export(combined_file, file_type="stl")
    _PROGRESS.complete("save_stl", f"Saved STL: {combined_file.name}")
    print(f"[INFO] Exported STL with terrain: {combined_file.resolve()}")

    # Report statistics
    minx, miny, maxx, maxy = base_final.bounds
    corners = [
        (minx, miny),
        (maxx, miny),
        (maxx, maxy),
        (minx, maxy)
    ]
    print("[RESULT] Base rectangle corners in meters")
    print(f"[RESULT] Lower left: ({corners[0][0]:.3f}, {corners[0][1]:.3f})")
    print(f"[RESULT] Lower right: ({corners[1][0]:.3f}, {corners[1][1]:.3f})")
    print(f"[RESULT] Upper right: ({corners[2][0]:.3f}, {corners[2][1]:.3f})")
    print(f"[RESULT] Upper left: ({corners[3][0]:.3f}, {corners[3][1]:.3f})")

    min_bounds, max_bounds = final_mesh.bounds
    zmin = float(min_bounds[2])
    zmax = float(max_bounds[2])
    print(f"[RESULT] STL Z range: min {zmin:.3f}m, max {zmax:.3f}m")
    print(f"[RESULT] Total height: {(zmax - zmin):.3f}m")
    program_elapsed = time.time() - program_start_time
    print(f"[INFO] Program total time: {program_elapsed:.2f} seconds")

if __name__ == "__main__":
    main()


